### ISSUE TITLE
Timeline: destroy() fails if groupTemplate option is overwritten

### ISSUE THREAD

**Issue by levzem** [almende/vis#3337]
Hi,

I am working with timeline (4.20) in chrome 59 on windows 7.

https://jsbin.com/puhekojozu/edit?html,js,output

Found another bug.

It seems that if you overwrite your own groupTemplate function and do not handle null groups, the destroy method fails. I do not think that destroy() should be calling the overwritten groupTemplate and if it should, perhaps it should reset all options to default first, so that this error does not occur. The corresponding jsbin is attached above.

Thanks

**Comment by yotamberk** [comment]
Thanks for reporting

**Comment by phil294** [comment]
I can confirm this bug. In 4.21, the stack trace is like this and perfectly demonstrates the problem:

core.js:1374 ERROR TypeError: Cannot read property 'content' of null
    at Group.groupTemplate (charging-timeline-chart.component.ts:222)
    at Group.setData (vis.js:11872)
    at new Group (vis.js:11819)
    at ItemSet._updateUngrouped (vis.js:18231)
    at ItemSet.setGroups (vis.js:18370)
    at Timeline.setGroups (vis.js:40930)
    at Timeline.Core.destroy (vis.js:9908)
    at setTimeout (charging-timeline-chart.component.ts:264)
    at ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:4006)

**Comment by tmalatinszki** [comment]
Are there any news about this one?
