### ISSUE TITLE
Editing groups doesn't work

### ISSUE THREAD

**Issue by yotamberk** [almende/vis#2367]
Trying to drag groups when `groupEditable: true` doesn't work.

Uncaught TypeError: this.groupsData.update is not a function(…)

occurs in the console log.

**Comment by yotamberk** [comment]
introduced in #2315

**Comment by yotamberk** [comment]
@simo9000 can you take care of this please? it seems like the problem is comes from  https://github.com/almende/vis/pull/2315/files#diff-b6d6829c0beaea329845d1d6610f2be0R269

**Comment by yotamberk** [comment]
nvm, I solved it

**Comment by mojoaxel** [comment]
this was fixed by @yotamberk with #2368
