### ISSUE TITLE
showCustomTime giving error

### ISSUE THREAD

**Issue by jmls** [almende/vis#1438]
I have the following code :

```javascript 
var options = { showCurrentTime: true,
  	    	showCustomTime: true
}
```
This has worked in the past using v3.10. However, using v4.9.0 I am now getting this error message on the console

```html
Unknown option detected: "showCustomTime". Did you mean "showCurrentTime"?

Problem value found at: 
options = {
  showCustomTime
}
vis.js:10191 Errors have been found in the supplied options object.
```

has this option changed ?

**Comment by AlexDM0** [comment]
Yes, 4.x was a breaking change. All options can be changed. There is a checker to help out if you supply an invalid option. 

Please read the documentation for more information. All the examples have also been updated.

Cheers

**Comment by jmls** [comment]
dammit. just found this in the history.md

"Deprecated option showCustomTime. Use method addCustomTime() instead."

**Comment by AlexDM0** [comment]
Remember you also need to update the css file. It will not work nicely with the old css.
